//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helppls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayDone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayDone()
        {
            this.PayType = new HashSet<PayType>();
        }
    
        public int Id { get; set; }
        public int BillId { get; set; }
        public string Service { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Bill Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayType> PayType { get; set; }
    }
}
